### ISSUE TITLE
MessagingException: Unable to load BODYSTRUCTURE

### ISSUE THREAD

**Issue by martinfrancois** [javaee/javamail#282]
When trying the following:
```
BodyPart messageBodyPart = new MimeBodyPart();
messageBodyPart.setDataHandler(message.getDataHandler());
```
I've got the following exception and stack trace when it tries to run the second line from the code snippet above (which represents EmailHandler.java:266 in the stack trace):
```
18:30:07.134 [main] TRACE martinfrancois.EmailHandler: forwardMessage (247) - Forwarding Messages...
A7 FETCH 1 (ENVELOPE INTERNALDATE RFC822.SIZE)
* 1 FETCH (ENVELOPE ("Wed, 13 Sep 2017 22:23:37 +0000" "=?UTF-8?B?IFMvdG9wIEIvYWNrIFAvYWluTk9XIQ===?=" (("=?UTF-8?B?VW5sb2NraW5nIEhpcCBGbGV4b3Jz=?=" NIL "BackPain_Experts_oxhj" "perfito.space")) NIL NIL NIL NIL NIL NIL "<549887338.0847844778059.t.mgeeznbyixybfcmjfbuy@perfito.space>") INTERNALDATE "13-Sep-2017 22:23:39 +0000" RFC822.SIZE 35269)
A7 OK FETCH completed.
18:30:07.287 [main] TRACE martinfrancois.EmailHandler: forwardMessage (253) - Subject:  S/top B/ack P/ainNOW!, Date: Thu Sep 14 00:23:37 CEST 2017
A8 FETCH 1 (BODYSTRUCTURE)
* 1 FETCH (BODYSTRUCTURE ("multipart" "signed" ("boundary" "_9bc333e9-3a24-4740-8211-a395c5448479_") NIL NIL "7BIT" -1 NIL NIL NIL NIL))
DEBUG IMAP: ignoring bad response, THROW: 
com.sun.mail.iap.ParsingException: BODYSTRUCTURE parse error: bad ``size'' element
	at com.sun.mail.imap.protocol.BODYSTRUCTURE.<init>(BODYSTRUCTURE.java:261)
	at com.sun.mail.imap.protocol.FetchResponse.parseItem(FetchResponse.java:256)
	at com.sun.mail.imap.protocol.FetchResponse.parse(FetchResponse.java:212)
	at com.sun.mail.imap.protocol.FetchResponse.<init>(FetchResponse.java:96)
	at com.sun.mail.imap.protocol.IMAPProtocol.readResponse(IMAPProtocol.java:409)
	at com.sun.mail.iap.Protocol.command(Protocol.java:355)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetch(IMAPProtocol.java:2151)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetch(IMAPProtocol.java:2143)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetchBodyStructure(IMAPProtocol.java:1717)
	at com.sun.mail.imap.IMAPMessage.loadBODYSTRUCTURE(IMAPMessage.java:1552)
	at com.sun.mail.imap.IMAPMessage.getDataHandler(IMAPMessage.java:808)
	at martinfrancois.EmailHandler.forwardMessage(EmailHandler.java:266)
	at martinfrancois.EmailHandler.moveMessages(EmailHandler.java:160)
	at martinfrancois.EmailHandler.moveSpam(EmailHandler.java:92)
	at martinfrancois.EmailHandler.main(EmailHandler.java:76)
A8 OK FETCH completed.
DEBUG IMAP: IMAPProtocol noop
A9 NOOP
A9 OK NOOP completed.
18:30:07.510 [main] ERROR martinfrancois.EmailHandler: forwardMessage (278) - MessagingException: Unable to load BODYSTRUCTURE
```

Any ideas on why this is happening?

**Comment by bshannon** [comment]
It's a completely bogus BODYSTRUCTURE response.  The server is broken.  Please report this problem to the server vendor.  Is this a Microsoft Exchange server?

You can try the [workaround described in the JavaMail FAQ](https://javaee.github.io/javamail/FAQ#imapserverbug).
