### ISSUE TITLE
SubjectTerm -  javax.mail.MessagingException: A4 BAD invalid command or parameters

### ISSUE THREAD

**Issue by zhangysh1995** [javaee/javamail#300]
I want to use `AndTerm` for searching unread mails with subject matching some words, but get the exception.
```
            Folder folder = store.getFolder("Inbox");
            folder.open(Folder.READ_ONLY);

            // search for "unread" messages
            Flags unread = new Flags(Flags.Flag.SEEN);
            FlagTerm unreadFlagTerm = new FlagTerm(unread, false);  // this works well

            // search for "cyy" in subject
            SearchTerm searchTerm = new AndTerm(unreadFlagTerm, new SubjectTerm("cyy"));

            Message[] messages = folder.search(subjectSearch);
```

Exception message:
```
javax.mail.MessagingException: A4 BAD invalid command or parameters;
  nested exception is:
	com.sun.mail.iap.BadCommandException: A4 BAD invalid command or parameters
	at com.sun.mail.imap.IMAPFolder.search(IMAPFolder.java:2391)
	at Utility.MailHandler.receive(MailHandler.java:154)
	at Utility.MailHandler.receiveMessage(MailHandler.java:116)
	at Mail.BasicMail.testRecv(BasicMail.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.sun.mail.iap.BadCommandException: A4 BAD invalid command or parameters
	at com.sun.mail.iap.Protocol.handleResult(Protocol.java:399)
	at com.sun.mail.imap.protocol.IMAPProtocol.issueSearch(IMAPProtocol.java:2587)
	at com.sun.mail.imap.protocol.IMAPProtocol.search(IMAPProtocol.java:2493)
	at com.sun.mail.imap.protocol.IMAPProtocol.search(IMAPProtocol.java:2480)
	at com.sun.mail.imap.IMAPFolder.search(IMAPFolder.java:2373)
	... 25 more
```

The `unread` flag works well and give correct output. The `SubjectTerm` doesn't work singly:

`SearchTerm subjectSearch = new SubjectTerm("cyy");`

I think this problem isn't about encoding, because I could use other APIs to get Message correctly without exception.

**Comment by bshannon** [comment]
It looks like the mail server is broken.  Which mail server are you using?

What does the [JavaMail debug output](https://javaee.github.io/javamail/FAQ#debug) show?
