### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by sergey-morenets** [javaee/javamail#301]
Hi 

Do you have plans to support JDK 9? We tried to migrate our project from JDK 8 to JDK 9 but encountered the followin exception afterwards:

```
Caused by: java.lang.NoClassDefFoundError: com/sun/mail/util/PropUtil
	at javax.mail.internet.ParameterList.<clinit>(ParameterList.java:144) ~[javax.mail-api-1.6.0.jar:1.6.0]
	at javax.mail.internet.ContentType.setParameter(ContentType.java:198) ~[javax.mail-api-1.6.0.jar:1.6.0]
	at javax.mail.internet.MimeMultipart.<init>(MimeMultipart.java:214) ~[javax.mail-api-1.6.0.jar:1.6.0]
	at javax.mail.internet.MimeMultipart.<init>(MimeMultipart.java:193) ~[javax.mail-api-1.6.0.jar:1.6.0]
```

The issue seems to occur because JDK 9 doesn't contain mentioned classes (PropUtil and many others from com.sun,main.util package)

The latest JavaMail library (1.6) was released in July 2017. 
Please advise.

**Comment by bshannon** [comment]
[As explained on the JavaMail project page](https://javaee.github.io/javamail/#Download_JavaMail_Release), that's because you're using the javax.mail-api jar file,
which is only intended for compiling.

To run the program you need the com.sun.mail:javax.mail artifact.
